# Generated by Django 5.2.7 on 2025-11-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='transportation_type',
            field=models.CharField(default='Air', max_length=50),
        ),
    ]
