# Generated by Django 5.2.7 on 2025-11-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_trip_price_trip_transportation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
