# Generated by Django 5.2.7 on 2025-11-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalid',
            name='detected_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
